### ISSUE TITLE
Filter not applied to gallery view

### ISSUE THREAD

**Issue by ngraf** [Visual-Regression-Tracker/frontend#181]
**Current state**
Given I open a build 
When I filter for "unresolved"
![image](https://user-images.githubusercontent.com/7094389/117271317-56b62780-ae5a-11eb-863e-f9106ab55fca.png)
And I open gallery view by clicking on an "unresolved" diff
And I click on ">" to go to next item
Then I will encounter "ok" items as well.
![image](https://user-images.githubusercontent.com/7094389/117271395-6cc3e800-ae5a-11eb-8f94-453ea14196a2.png)

**Desired state**
Then I will only encounter "unresolved" items since I filtered for them and I do not want to my waste time iterating over "ok" items making it more likely I will do human mistakes here.

**Comment by pashidlos** [comment]
@ngraf thanks for the request 
this one will be fixed in scope of https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/260

**Comment by ngraf** [comment]
perfect, thanks
