### ISSUE TITLE
Cannot start front end on Linux or Windows WSL

### ISSUE THREAD

**Issue by polyvisual** [Visual-Regression-Tracker/frontend#310]
Following https://github.com/Visual-Regression-Tracker/frontend/blob/master/README.md

At the step `npm run start` on Linux (Ubuntu server) and Windows WSL, the following error is displayed

```
> vrt-frontend@1.6.0 start
> chmod +x ./env.sh && sh ./env.sh && cp env-config.js ./public/ && react-scripts start

./env.sh: 22: Bad substitution
./env.sh: 24: [[: not found
./env.sh: 22: Bad substitution
./env.sh: 24: [[: not found
./env.sh: 13: [[: not found
```

It's trying to run dash /bin/dash and the substitution is breaking on Linux and Windows WSL. mac is fine, though.

To fix this, remove the `sh` from https://github.com/Visual-Regression-Tracker/frontend/blob/a373f865b9bdf2109e573fac3b7e0102a28341f0/package.json#L39

```
"start": "chmod +x ./env.sh && ./env.sh && cp env-config.js ./public/ && react-scripts start",
```

Alternatively remove this section from `package.json` and move it to the readme document

```
chmod +x ./env.sh && ./env.sh && cp env-config.js ./public/
```

**Comment by paazmaya** [comment]
The bash script which creates an environment variable file in JavaScript, should be migrated to be a Node.js script.
This would allow it to be used anywhere.
