### ISSUE TITLE
React does not recognize the `data-testId` prop on a DOM element

### ISSUE THREAD

**Issue by paazmaya** [Visual-Regression-Tracker/frontend#324]
Running `npm start` reveals the following warning in the console:

> Warning: React does not recognize the `data-testId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-testid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

This was recently changed in the Playwright migration, perhaps @pashidlos you have idea why id was capitalised?

**Comment by pashidlos** [comment]
`data-testId` is default attribute for playwright https://playwright.dev/docs/api/class-testoptions#test-options-test-id-attribute
seems there is no difference if it's in upper case or not so we could make it lower score

**Comment by paazmaya** [comment]
Did we read the same version of that page?

> Custom attribute to be used in [page.getByTestId()](https://playwright.dev/docs/api/class-page#page-get-by-test-id). data-testid is used by default.
